// <auto-generated />
using System;
using FlightInformationApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightInformationApi.Migrations
{
    [DbContext(typeof(WriteContext))]
    partial class WriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FlightInformationApi.Data.Airport", b =>
                {
                    b.Property<int>("AirportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("AirportID");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightInformationApi.Data.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Airline")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArrivalAirportAirportID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartureAirportAirportID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightID");

                    b.HasIndex("ArrivalAirportAirportID");

                    b.HasIndex("DepartureAirportAirportID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightInformationApi.Data.Flight", b =>
                {
                    b.HasOne("FlightInformationApi.Data.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportAirportID");

                    b.HasOne("FlightInformationApi.Data.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportAirportID");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });
#pragma warning restore 612, 618
        }
    }
}
